### PR TITLE
fix: join next link instead of append for pagination in get_tags

### PR DESCRIPTION
**Pull request by natefaerber**
Resolves https://github.com/oras-project/oras-py/issues/173

Some simple testing (see original issue for reproduction):

```
>>> tags = client.get_tags('my/image')
>>> len(tags)
3232
>>> tags = client.get_tags('my/image', N=100)
>>> len(tags)
100
>>> tags = client.get_tags('my/image', N=1)
>>> len(tags)
1
>>> tags = client.get_tags('my/other_image')
>>> len(tags)
5
>>> tags = client.get_tags('my/other_image', N=10)
>>> len(tags)
5
>>> tags = client.get_tags('my/other_image', N=1)
>>> len(tags)
1
```

Note that an error will still occur when passing `N > 1000` but I'm not trying to add that guardrail here.

### CODE REVIEW

**Comment by vsoch** [comment]
This looks good - pending tests passing, would you please bump the version and update the CHANGELOG.md with the corresponding version and a note about the change?

**Comment by natefaerber** [comment]
> This looks good - pending tests passing, would you please bump the version and update the CHANGELOG.md with the corresponding version and a note about the change?

I can do that. I wasn't sure (didn't actually check) if that was part of the process. Coming soon.

**Comment by vsoch** [comment]
> I can do that. I wasn't sure (didn't actually check) if that was part of the process. Coming soon.

That's a good point! I can add a note to the readme about it.

**Comment by natefaerber** [comment]
@vsoch , I think I need some guidance after all. I see this in the CHANGELOG.md

> check for blob existence before uploading (0.2.26)

But the version in main is `0.2.25`

Do you expect me to add this PR as `0.2.27` or as a second feature of unreleased `0.2.26`?

**Comment by vsoch** [comment]
That means the release isn't done yet - so you can add an indentation under 0.2.26 with your change. We can do the release this time, so feel free to bump the version too.

**Comment by natefaerber** [comment]
I have pushed a commit with updated CHANGELOG and version bumped but if you want to wait a bit. I can provide a PR to fix https://github.com/oras-project/oras-py/issues/167.

**Comment by vsoch** [comment]
We can do that in a separate PR (and I'll hold off on the release if you want to do it to add it). Thanks @natefaerber !

**Review by vsoch — APPROVED** [review]

**Comment by natefaerber** [comment]
Here that other PR: https://github.com/oras-project/oras-py/pull/176

**Pull request merged**
