### PR TITLE
Docker optional dependency

### PR DESCRIPTION
**Pull request by vsoch**
We currently are just using it for login and finding configs, and since osx on conda does not have it (and we want to support it) it makes sense to have docker be optional, meaning we fall back to manual ways to do the same thing. I am leaving it as an extra variant for now in case someone prefers using docker, however if we have confidence it is not needed it can be removed entirely.

See https://github.com/conda-forge/oras-py-feedstock/issues/1 and ping @wolfv

### CODE REVIEW

**Comment by wolfv** [comment]
Awesome! I think the regular OS X 64 on conda-forge has it, just the osx-arm64 (M1) chip not yet.

**Comment by vsoch** [comment]
Ah gotcha! Also I was testing newer versions of docker (on Linux/Ubuntu) and the function behavior wasn't consistent (e.g., updating broke some functions) so that is what first incentivized me to want to remove it / make it optional. Likely we will need a user that has a more complicated docker config setup to know if/what is missing.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by vsoch** [comment]
Thank you! I think we will need an admin approval (ping @sajayantony!) before the merge is allowed (and I'm not too keen on clicking the "merge without waiting for requirements to be met" box.

When this goes in, I'm planning to release after #32 is merged since it fixes some bugs with respect to pushing to GitHub packages. Then we will have a new release for conda-forge too!

**Comment by vsoch** [comment]
@wolfv I've just triggered a release, so I'll follow up on conda-forge to update the recipe to not require docker.

**Pull request merged**
