### PR TITLE
bugfix that pagination sets upper limit when should not!

### PR DESCRIPTION
**Pull request by vsoch**
@wolfv see the changes here - I removed the typing because it was really just hurting us more than helping!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by wolfv** [comment]
Hmm, I thought about pagination more and I think the `n` is actually OK because it just indicates how many to get per "page" (not in total). So maybe better to keep an arbitrarily high value to not use too many requests, but I haven't checked wether it makes a difference or not.

**Comment by vsoch** [comment]
> Hmm, I thought about pagination more and I think the n is actually OK because it just indicates how many to get per "page" (not in total). So maybe better to keep an arbitrarily high value to not use too many requests, but I haven't checked wether it makes a difference or not.

I think N is typically how many results to get - it would be strange to only get a subset per page (but then to paginate!)

**Comment by vsoch** [comment]
I updated the PR here to also include handling the case when tags is `null`. Let me know if we are ok to merge and release!

**Comment by wolfv** [comment]
Yeah but 'n' would also be used to set the elements per page. But it also doesn't matter much to me as ping as it works :)

**Comment by wolfv** [comment]
All good regarding merging and releasing btw!

**Comment by vsoch** [comment]
It would be confusing for n to set elements per page, but have the endpoint be different (the total):

image

I've implemented / used a lot of APIs and (I think)? the parameter you have in mind is usually called `per_page` or similar.  

Let's get this out!

**Pull request merged**
