### PR TITLE
fix bug when tags are `null`

### PR DESCRIPTION
**Pull request by wolfv**
unfortunately I discovered that `tags` can be `null`

### CODE REVIEW

**Comment by wolfv** [comment]
Also I was wondering if we should throw a different error type than `ValueError` when the HTTP request has a non-200 response? Maybe just throw whatever `requests` would throw?

**Comment by vsoch** [comment]
That would work.

**Comment by vsoch** [comment]
I fixed this bug in this branch so we can work off of one! https://github.com/oras-project/oras-py/pull/70/commits/8176eedefb061bd8ac14f24798fb49c0703fb6bb

**Comment by vsoch** [comment]
This was fixed in #70 - thanks @wolfv !

**Pull request closed without merging**
